
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/lut 

module andlut(b, a, y);
  input b, a;
  output y;
  wire b, a;
  wire y;
  AND2X1 g9(.A (b), .B (a), .Y (y));
endmodule

module orlut(b, a, y);
  input b, a;
  output y;
  wire b, a;
  wire y;
  OR2X1 g3(.A (a), .B (b), .Y (y));
endmodule

module xorlut(b, a, y);
  input b, a;
  output y;
  wire b, a;
  wire y;
  XOR2X4 g2(.A (b), .B (a), .Y (y));
endmodule

module lut(op1, op0, b, a, y);
  input op1, op0, b, a;
  output y;
  wire op1, op0, b, a;
  wire y;
  wire n_0, n_1, ya, yo, yx;
  andlut i1(b, a, ya);
  orlut i2(b, a, yo);
  xorlut i4(b, a, yx);
  MX4XL g61(.A (n_1), .B (ya), .C (yx), .D (yo), .S0 (n_0), .S1 (op0),
       .Y (y));
  CLKINVX4 g62(.A (a), .Y (n_1));
  CLKINVX4 g63(.A (op1), .Y (n_0));
endmodule

